#!/bin/csh -f

   if ($1 == min) then
    set CORNER=SDFMIN
    echo $CORNER
   else if ($1 == max) then
    set CORNER=SDFMAX
    echo $CORNER
   else
    echo Usage: $0  min/max
    exit
   endif

   setenv INCISIV_VER 14.10.008_Hotfix;
   limit stacksize 8192

   nc run -r+ RAM/80000 -r+ CORES/1 -- \
   ncverilog  \
   +sv  \
   -processor 4 \
   +ncnontcglitch \
   +nclicq \
   +libext+.v \
   +ncinput+inter_tdf_los_int_parallel.i \
   +message \
   +update \
   +nc64bit \
   +nclibdirname+INCA_tdf_los_int_parallel_$CORNER \
   +status \
   +access+rwc \
   +ncgateloopwarn \
   +ncaccess+c \
   +ncgateloopwarn \
   +nctimescale+'1ns/1ps' \
 # +ncseq_udp_delay+5ps \
 # +delay_mode_path \
 # +delay_mode_distributed \
 # +delay_mode_unit \
 # +delay_mode_zero \
 # +notchkmsg \
 # +notimingcheck \
 # +nospecify \
 # +define+UNIT_DELAY \
   +define+NTC+RECREM \
   +define+no_warning \
   +define+PARALLEL \
   +define+$CORNER \
   +sdf_orig_dir \
#  +STARTPAT=                 # TK parallel patterns testbench supports start and end arguments \
#  +ENDPAT=    \
   -ALLOWREDEFINITION \
   -vlogext ".v" \
   -vlogext ".vlvs" \
   -f ./system_tdf_los_int_parallel.f \
      ./sdf_annotate_tdf_los_int_parallel.v \
   -log verilog_BLOCK_tdf_los__sdf_$CORNER.log 