set OCC_CLK_GATE(pll_937)  { 
    u_hcm_lif_u0_lif0_u0.lif0_gate_tessent_tdr_SCAN_TDR_inst.OCC_CLK_GATE_EN 
    u_hcm_lif_u0_lif0_u1.lif02_gate_tessent_tdr_SCAN_TDR_inst.OCC_CLK_GATE_EN 
    u_hcm_lif_u0_lif1_u0.lif1_gate_tessent_tdr_SCAN_TDR_inst.OCC_CLK_GATE_EN 
    u_hcm_lif_u0_lif12_u0.lif12_gate_tessent_tdr_SCAN_TDR_inst.OCC_CLK_GATE_EN 
    u_hcm_lif_u0_rce_24_ch_1_u0_falcon_top_v1_u0_pcs_top_v1_u0_fec_fec_tx.fec_tx_v1_gate_tessent_tdr_SCAN_TDR_inst.OCC_CLK_GATE_EN 
    u_hcm_lif_u0_rce_24_ch_u0_falcon_top_v0_u0_pcs_top_v0_u0_fec_fec_tx_v0.fec_tx_v0_gate_tessent_tdr_SCAN_TDR_inst.OCC_CLK_GATE_EN 
} 
