set OCC_CLK_GATE(rf_2pA_128x10)  { 
    u_hcm_lif_u0_rce_24_ch_u0_falcon_top_v0_u0_pcs_top_v0_u0_pcs.pcs_v0_gate_tessent_tdr_SCAN_TDR_inst.OCC_CLK_GATE_EN 
    u_hcm_lif_u0_rce_24_ch_1_u0_falcon_top_v1_u0_pcs_top_v1_u0_pcs.pcs_v1_gate_tessent_tdr_SCAN_TDR_inst.OCC_CLK_GATE_EN 
} 
set OCC_CLK_GATE(rf_2pA_120x11)  { 
    u_hcm_lif_u0_rce_24_ch_u0_falcon_top_v0_u0_flexe_v0_u0_flexe_tx_v0_u0_flexe_tx_wrapper_01_v0_u0.flexe_tx_wrapper_01_v0_gate_tessent_tdr_SCAN_TDR_inst.OCC_CLK_GATE_EN 
    u_hcm_lif_u0_rce_24_ch_1_u0_falcon_top_v1_u0_flexe_v1_u0_flexe_tx_v1_u0_flexe_tx_wrapper_01_v1_u0.flexe_tx_wrapper_01_v1_gate_tessent_tdr_SCAN_TDR_inst.OCC_CLK_GATE_EN 
} 
